version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.${NODE_ENV:-dev}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - DATABASE_URL=postgresql://user:password@db:5432/wallet_tracker
    volumes:
      - .:/app
      - /app/node_modules
    command: >
      sh -c "
        npm run prisma:generate &&
        npm run prisma:migrate &&
        npm run ${NODE_ENV:-dev}
      "
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wallet_tracker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d wallet_tracker"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: