version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.${NODE_ENV:-dev}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - DATABASE_URL=postgresql://user:password@db:5432/wallet_tracker
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run ${NODE_ENV:-dev}
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wallet_tracker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: