version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.${NODE_ENV:-dev}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run ${NODE_ENV:-dev}